name: stable_rm_classifier
channels:
  - conda-forge
  - defaults
dependencies:
  # Core system and Python
  - python==3.11.6
  - pip
  
  # Only essential system-level packages via conda
  - numpy==1.26.4
  - scipy==1.15.1

  # Everything else via pip (matches your requirements.txt exactly)
  - pip:
    - bokeh==3.6.0
    - joblib==1.4.2
    - keras==3.9.2
    - matplotlib==3.10.0
    - numba==0.61.0
    - pandas==2.2.3
    - PyYAML==6.0.2
    - scikit_learn==1.6.1
    - tensorflow==2.19.0
    - umap_learn==0.5.7
    - bottleneck==1.4.2
    - mkl-service==2.4.1
    - numexpr==2.10.1
    - memory_profiler==0.61.0